---
- name: Configure kernel modules and sysctl parameters for Kubernetes
  hosts: tag_role_kubecluster
  become: yes
  tasks:
    - name: Load kernel modules
      command: "{{ item }}"
      loop:
        - "echo overlay >> /etc/modules-load.d/k8s.conf"
        - "echo br_netfilter >> /etc/modules-load.d/k8s.conf"
      notify: Reload kernel modules

    - name: Load kernel modules immediately
      command: "{{ item }}"
      loop:
        - "modprobe overlay"
        - "modprobe br_netfilter"

    - name: Configure sysctl parameters
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        dest: /etc/sysctl.d/k8s.conf
      notify: Apply sysctl parameters

  handlers:
    - name: Reload kernel modules
      shell: "modprobe {{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Apply sysctl parameters
      command: sysctl --system
