---
- name: Configure MySQL Docker container
  hosts: localhost
  become: yes
  tasks:
    
    - name: Install urllib3 version 1.26.8
      pip:
        name: urllib3==1.26.8

    - name: docker-py install # 도커 python3 라이브러리 설치
      pip:
        name: docker-py
        executable: pip3

    - name: Run MySQL Docker container # mysql 도커 컨테이너 다운로드 및 설치
      docker_container:
        name: mysqldb
        image: mrsono0/mysql_5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: education
          MYSQL_DATABASE: guestbook
        ports:
          - "3306:3306"
