---
- name: install jenkins_ubuntu_install.yaml
  hosts: tag_OS_ubuntu
  become: true
  tasks:

    - name: Install ca-certificates package
      apt:
        name: ca-certificates
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Import Jenkins GPG key
      shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
      args:
        executable: /bin/bash

    - name: Add Jenkins repository
      shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      args:
        executable: /bin/bash

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Show Jenkins initialAdminPassword
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: shell_output

    - name: Print to console 
      debug: 
        msg: "{{ shell_output.stdout }}"