- name: install jenkins_ubuntu_install.yaml
  hosts: tag_OS_ubuntu
  become: true
  tasks:
    - name: Install ca-certificates package
      apt:
        name: ca-certificates
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Add Jenkins GPG key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 5BA31D57EF5975CA
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Show Jenkins initialAdminPassword
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: shell_output

    - name: Print to console 
      debug: 
        msg: "{{ shell_output.stdout }}"